## d

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse

print('numpy version : ', np.__version__)
print('pandas version : ', np.__version__)

numpy version :  1.19.2
pandas version :  1.19.2


In [12]:
def seriesInfo(ary) : 
    print('data \n', ary)
    print('index : ', type(ary.index), ary.index)
    print('value : ', type(ary.values), ary.values)

def frmInfo(df) :
    display('DataFrame : ', df)
    print('shape   : ', df.shape)
    print('size    : ', df.size)
    print('ndim    : ', df.ndim)
    print('index   : ', df.index, type(df.index))
    print('columns : ', df.columns, type(df.columns))
    print('values  : \n', df.values, type(df.values))

In [13]:
sample_frm = pd.DataFrame(np.arange(10,22).reshape(3,4),
                         index = ['a', 'b', 'c'],
                         columns = ['col01', 'col02', 'col03', 'col04'])
print(sample_frm)

   col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21


In [15]:
sample_frm.loc['a']

col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32

In [16]:
seriesInfo(sample_frm.loc['a'])

data 
 col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32
index :  <class 'pandas.core.indexes.base.Index'> Index(['col01', 'col02', 'col03', 'col04'], dtype='object')
value :  <class 'numpy.ndarray'> [10 11 12 13]


In [17]:
print(sample_frm.loc['a'].values, type(sample_frm.loc['a'].values))

[10 11 12 13] <class 'numpy.ndarray'>


In [24]:
frmInfo(sample_frm.loc[['a','c']])
frmInfo(sample_frm.loc[(1, 2)])

'DataFrame : '

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

shape   :  (2, 4)
size    :  8
ndim    :  2
index   :  Index(['a', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[10 11 12 13]
 [18 19 20 21]] <class 'numpy.ndarray'>


KeyError: 1

In [19]:
sample_frm['col01']

a    10
b    14
c    18
Name: col01, dtype: int32

In [25]:
sample_frm['col01'] > 15

a    False
b    False
c     True
Name: col01, dtype: bool

In [26]:
sample_frm.loc[sample_frm['col01']>15]

col01  col02  col03  col04
c     18     19     20     21

In [27]:
print(type(sample_frm.loc['a','col01']), sample_frm.loc['a', 'col01'])

<class 'numpy.int32'> 10


In [28]:
print(type(sample_frm.loc['a':'b','col01']), sample_frm.loc['a':'b', 'col01'])

<class 'pandas.core.series.Series'> a    10
b    14
Name: col01, dtype: int32


In [29]:
frmInfo(sample_frm)

'DataFrame : '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

shape   :  (3, 4)
size    :  12
ndim    :  2
index   :  Index(['a', 'b', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]] <class 'numpy.ndarray'>


In [31]:
sample_frm.loc[:, 'col01']

a    10
b    14
c    18
Name: col01, dtype: int32

In [32]:
sample_frm.iloc[0, -2:0]

Series([], Name: a, dtype: int32)

In [33]:
sample_frm.iloc[-1]

col01    18
col02    19
col03    20
col04    21
Name: c, dtype: int32

In [34]:
sample_frm.iloc[-1] = sample_frm.iloc[-1]*2
frmInfo(sample_frm)

'DataFrame : '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42

shape   :  (3, 4)
size    :  12
ndim    :  2
index   :  Index(['a', 'b', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[10 11 12 13]
 [14 15 16 17]
 [36 38 40 42]] <class 'numpy.ndarray'>


In [35]:
sample_frm.loc['d'] = 0
frmInfo(sample_frm)

'DataFrame : '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42
d      0      0      0      0

shape   :  (4, 4)
size    :  16
ndim    :  2
index   :  Index(['a', 'b', 'c', 'd'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[10 11 12 13]
 [14 15 16 17]
 [36 38 40 42]
 [ 0  0  0  0]] <class 'numpy.ndarray'>


In [36]:
sample_frm.loc['e'] = sample_frm.loc['d']
frmInfo(sample_frm)

'DataFrame : '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42
d      0      0      0      0
e      0      0      0      0

shape   :  (5, 4)
size    :  20
ndim    :  2
index   :  Index(['a', 'b', 'c', 'd', 'e'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[10 11 12 13]
 [14 15 16 17]
 [36 38 40 42]
 [ 0  0  0  0]
 [ 0  0  0  0]] <class 'numpy.ndarray'>


In [41]:
sample_frm.loc['d'] = [1,3,5,7]
frmInfo(sample_frm)

'DataFrame : '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42
d      1      3      5      7
e      0      0      0      0

shape   :  (5, 4)
size    :  20
ndim    :  2
index   :  Index(['a', 'b', 'c', 'd', 'e'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[10 11 12 13]
 [14 15 16 17]
 [36 38 40 42]
 [ 1  3  5  7]
 [ 0  0  0  0]] <class 'numpy.ndarray'>


In [43]:
# 새로운 열 추가
sample_frm['col05'] = sample_frm['col04']
frmInfo(sample_frm)

'DataFrame : '

col01  col02  col03  col04  col05
a     10     11     12     13     13
b     14     15     16     17     17
c     36     38     40     42     42
d      1      3      5      7      7
e      0      0      0      0      0

shape   :  (5, 5)
size    :  25
ndim    :  2
index   :  Index(['a', 'b', 'c', 'd', 'e'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04', 'col05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[10 11 12 13 13]
 [14 15 16 17 17]
 [36 38 40 42 42]
 [ 1  3  5  7  7]
 [ 0  0  0  0  0]] <class 'numpy.ndarray'>


In [52]:
sample_frm.iloc[1,1]

15

In [53]:
sample_frm.iloc[1][1]

15

In [56]:
score_data = {
    'kor'  : [80,90,70,30],
    'eng'  : [90,70,60,40],
    'math' : [90,60,90,70] 
}
columns = ['kor','eng','math']
index   = ['김지은', '황인범', '김정수', '최호진']

score_frm = pd.DataFrame(score_data, index=index, columns=columns)
frmInfo(score_frm)

'DataFrame : '

kor  eng  math
김지은   80   90    90
황인범   90   70    60
김정수   70   60    90
최호진   30   40    70

shape   :  (4, 3)
size    :  12
ndim    :  2
index   :  Index(['김지은', '황인범', '김정수', '최호진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['kor', 'eng', 'math'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[80 90 90]
 [90 70 60]
 [70 60 90]
 [30 40 70]] <class 'numpy.ndarray'>


In [57]:
# 01 모든 학생의 각 과목 평균 점수를 새로운 열로 추가하라
# 02 최호진 학생의 영어 점수를 90점으로 수정하고 평균 점수도 다시 계산하라
# 03 김지은 학생의 점수를 데이터 프레임으로 만들어라
# 04 김정수 학생의 점수를 시리즈로 출력하라
# 05 황인범 학생의 국어점수와 수학점수를 100점으로 수정하고 평균 점수도 다시 계산하라

In [113]:
score_frm['average'] = np.mean(score_frm, axis=1).round(2)
frmInfo(score_frm)

'DataFrame : '

kor  eng  math  average
김지은   80   90    90    86.67
황인범   90   70    60    73.33
김정수   70   60    90    73.33
최호진   30   40    70    46.67

shape   :  (4, 4)
size    :  16
ndim    :  2
index   :  Index(['김지은', '황인범', '김정수', '최호진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['kor', 'eng', 'math', 'average'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[80.   90.   90.   86.67]
 [90.   70.   60.   73.33]
 [70.   60.   90.   73.33]
 [30.   40.   70.   46.67]] <class 'numpy.ndarray'>


In [114]:
np.mean(score_frm).T

kor        67.5
eng        65.0
math       77.5
average    70.0
dtype: float64

In [ ]:
scor_frm.loc['황인범', ['kor', 'maht']] =100

- 데이터프레임 조작, count

In [116]:
tmp_series = pd.Series(range(10))
tmp_series[5] = np.NaN
tmp_series.count()

9

In [120]:
cnt_frm = pd.DataFrame(np.random.randn((5,size=4,4))
cnt_frm

SyntaxError: invalid syntax (<ipython-input-120-8bc534aff2cd>, line 1)

#### 타이타닉 데이터를 이용한 [실습]

In [125]:
import seaborn as sns
datasets = sns.load_dataset('titanic')
print('type : ')
print(type(datasets))

type : 
<class 'pandas.core.frame.DataFrame'>


In [126]:
titanic_dataset = pd.read_csv('./data/titanic_train.csv')
print('type : ')
print(type(titanic_dataset))

type : 
<class 'pandas.core.frame.DataFrame'>


In [127]:
frmInfo(datasets)

'DataFrame : '

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

shape   :  (891, 15)
size    :  13365
ndim    :  2
index   :  RangeIndex(start=0, stop=891, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns :  Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[0 3 'male' ... 'Southampton' 'no' False]
 [1 1 'female' ... 'Cherbourg' 'yes' False]
 [1 3 'female' ... 'Southampton' 'yes' True]
 ...
 [0 3 'female' ... 'Southampton' 'no' False]
 [1 1 'male' ... 'Cherbourg' 'yes' True]
 [0 3 'male' ... 'Queenstown' 'no' True]] <class 'numpy.ndarray'>


In [128]:
frmInfo(titanic_dataset)

'DataFrame : '

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

shape   :  (891, 12)
size    :  10692
ndim    :  2
index   :  RangeIndex(start=0, stop=891, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns :  Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>
values  : 
 [[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']] <class 'numpy.ndarray'>


In [129]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [130]:
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [131]:
datasets.count

<bound method DataFrame.count of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_

In [132]:
datasets.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [133]:
datasets['pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: int64

In [134]:
datasets_drop_frm = datasets.drop([0,1,2], axis = 0, inplace = False)
datasets_drop_frm.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False

In [135]:
datasets.index[: 10].values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [136]:
datasets.columns[: 10].values

array(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who'], dtype=object)

In [138]:
fare_series = datasets['fare']
print('type : ', type(fare_series))
print()
print('values type : ', type(fare_series.values))

print()
print('max : ', fare_series.max())
print('min : ', fare_series.min())
print('sum : ', fare_series.sum())

type :  <class 'pandas.core.series.Series'>

values type :  <class 'numpy.ndarray'>

max :  512.3292
min :  0.0
sum :  28693.9493


- 인덱스를 재정의하는 방법
- reset_index() : 새로운 인덱스 할당, 기존 인덱스를 열로 추가하는 방법

In [146]:
reset_index_frm = datasets_drop_frm.reset_index(inplace = False)
reset_index_frm.head(10)

level_0  index  survived  pclass     sex   age  sibsp  parch     fare  \
0        0      3         1       1  female  35.0      1      0  53.1000   
1        1      4         0       3    male  35.0      0      0   8.0500   
2        2      5         0       3    male   NaN      0      0   8.4583   
3        3      6         0       1    male  54.0      0      0  51.8625   
4        4      7         0       3    male   2.0      3      1  21.0750   
5        5      8         1       3  female  27.0      0      2  11.1333   
6        6      9         1       2  female  14.0      1      0  30.0708   
7        7     10         1       3  female   4.0      1      1  16.7000   
8        8     11         1       1  female  58.0      0      0  26.5500   
9        9     12         0       3    male  20.0      0      0   8.0500   

  embarked   class    who  adult_male deck  embark_town alive  alone  
0        S   First  woman       False    C  Southampton   yes  False  
1        S   Third    man        True  NaN  Southampton    no   True  
2        Q   Third    man        True  NaN   Queenstown    no   True  
3        S   First    man        True    E  Southampton    no   True  
4        S   Third  child       False  NaN  Southampton    no  False  
5        S   Third  woman       False  NaN  Southampton   yes  False  
6        C  Second  child       False  NaN    Cherbourg   yes  False  
7        S   Third  child       False    G  Southampton   yes  False  
8        S   First  woman       False    C  Southampton   yes   True  
9        S   Third    man        True  NaN  Southampton    no   True

In [147]:
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [148]:
# pclass == 3 인 데이터만 확인하기
# boolean_index

# 선실등급이 3등급인 승객의 sex, who 확인하기
boolean_idx = datasets['pclass'] == 3
datasets[boolean_idx].iloc[0:10, [2,9]]

sex    who
0     male    man
2   female  woman
4     male    man
5     male    man
7     male  child
8   female  woman
10  female  child
12    male    man
13    male    man
14  female  child

#### year2020_baby_name.csv 실습

In [151]:
name_dataset = pd.read_csv('./data/year2020_baby_name.csv')
print('type : ')
print(type(name_dataset))
print()
name_dataset.info()

type : 
<class 'pandas.core.frame.DataFrame'>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33838 entries, 0 to 33837
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   NAME    33838 non-null  object
 1   GENDER  33838 non-null  object
 2   COUNT   33838 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 793.2+ KB


In [152]:
name_dataset.head()

NAME GENDER  COUNT
0  Isabella      F  22731
1    Sophia      F  20477
2      Emma      F  17179
3    Olivia      F  16860
4       Ava      F  15300

In [172]:
sort_name_dataset = name_dataset.sort_values(by='COUNT', ascending=False)
sort_name_dataset.head()

NAME GENDER  COUNT
0      Isabella      F  22731
19698     Jacob      M  21875
1        Sophia      F  20477
19699     Ethan      M  17866
2          Emma      F  17179

In [173]:
sort_name_dataset.reset_index(inplace=True)
sort_name_dataset

index      NAME GENDER  COUNT
0          0  Isabella      F  22731
1      19698     Jacob      M  21875
2          1    Sophia      F  20477
3      19699     Ethan      M  17866
4          2      Emma      F  17179
...      ...       ...    ...    ...
33833  18743  Mccauley      F      5
33834  18742     Mazal      F      5
33835  18741    Mayzee      F      5
33836  18740    Maythe      F      5
33837  33837     Zzyzx      M      5

[33838 rows x 4 columns]

In [177]:
sort_name_dataset.drop(['index'], axis=1, inplace=True)
sort_name_dataset

NAME GENDER  COUNT
0      Isabella      F  22731
1         Jacob      M  21875
2        Sophia      F  20477
3         Ethan      M  17866
4          Emma      F  17179
...         ...    ...    ...
33833  Mccauley      F      5
33834     Mazal      F      5
33835    Mayzee      F      5
33836    Maythe      F      5
33837     Zzyzx      M      5

[33838 rows x 3 columns]

In [179]:
rank_series = sort_name_dataset['COUNT'].rank(ascending=False)
rank_series

0            1.0
1            2.0
2            3.0
3            4.0
4            5.0
          ...   
33833    31407.5
33834    31407.5
33835    31407.5
33836    31407.5
33837    31407.5
Name: COUNT, Length: 33838, dtype: float64

In [180]:
rank = rank_series.astype('int64')
sort_name_dataset['rank'] = rank

In [181]:
sort_name_dataset

NAME GENDER  COUNT   rank
0      Isabella      F  22731      1
1         Jacob      M  21875      2
2        Sophia      F  20477      3
3         Ethan      M  17866      4
4          Emma      F  17179      5
...         ...    ...    ...    ...
33833  Mccauley      F      5  31407
33834     Mazal      F      5  31407
33835    Mayzee      F      5  31407
33836    Maythe      F      5  31407
33837     Zzyzx      M      5  31407

[33838 rows x 4 columns]

In [182]:
m_gender_frm = sort_name_dataset[sort_name_dataset['GENDER'] == 'M']
f_gender_frm = sort_name_dataset[sort_name_dataset['GENDER'] == 'F']

In [183]:
m_gender_frm

NAME GENDER  COUNT   rank
1        Jacob      M  21875      2
3        Ethan      M  17866      4
5      Michael      M  17133      6
6       Jayden      M  17030      7
7      William      M  16870      8
...        ...    ...    ...    ...
30978   Kaspar      M      5  31407
30979  Kasimir      M      5  31407
30980  Kashtyn      M      5  31407
30981    Rijul      M      5  31407
33837    Zzyzx      M      5  31407

[14140 rows x 4 columns]

Empty DataFrame
Columns: [NAME, GENDER, COUNT, rank]
Index: []